# What is the total revenue generated by male vs female customers ?
select gender, sum(purchase_amount) as revenue
from my_table
group by gender;

#which customers used a discount but stil spent more the average purchase amount?
SELECT customer_id, purchase_amount
FROM my_table
WHERE discount_applied = 'Yes'
  AND purchase_amount >= (
      SELECT AVG(purchase_amount)
      FROM my_table
  );

# which are the top 5 products with the highest average review rating?
select item_purchased, Round(avg(review_rating),2) as "Average Product Rating"
from my_table
group by item_purchased
order by avg(review_rating) desc	
limit 5;

#Compare the average Purchase Amounts between standard and express shipping.
select shipping_type,
Round(AVG(purchase_amount),2)
from my_table
where shipping_type in ('Standard', 'Express')
group by shipping_type;

# Do subscribed customers spend more? compare average spend and total revenue betweensubscribers and non-subscribers.
Select subscription_status,
COUNT(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from my_table
group by subscription_status
order by total_revenue , avg_spend desc;

#Which 5 products have the highest percentage of purchase with discounts applied?
select item_purchased,
Round(sum(case when discount_applied = 'Yes' then 1 else 0 end) /count(*) * 100,2) as discount_rate
from my_table
group by item_purchased
order by discount_rate desc
limit 5;

# segment customers into New , returning, and loyal based on their total number of previous purchases, and show the count of each segemnt.
with customer_type as (
select customer_id, previous_purchases,
case	
	when previous_purchases = 1 THEN 'New'
    when previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    else 'loyal'
    end as customer_segment
from my_table
)
select customer_segment, count(*) as "Number of customers"
from customer_type
group by customer_segment;


# what are the top 3 most purchased products within each category?
with item_counts as (
select category ,
item_purchased,
count(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) DESC) as item_rank 
from my_table
group by category , item_purchased )
select item_rank, category , item_purchased, total_orders
from item_counts 
where item_rank <= 3;


# Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from my_table
where previous_purchases > 5
group by subscription_status;


#what is the revenue contribution of each age group?
select age_group,
sum(purchase_amount) as total_revenue
from my_table
group by age_group
order by total_revenue desc;













































